### ISSUE TITLE
Custom Texture Packs (imgur support)

### ISSUE THREAD

**Issue by MagicPigeon** [bash-tp/tagpro-vcr#5]
Would be really nice to have the option to use custom textures for recording competitive games. The jersey script swaps ball textures for team uniforms, but it doesn't work with VCRs. If we could link custom texture packs we could just edit those to add team jerseys and that'd work as well.

Jersey script: https://github.com/MagicPigeon/ECLTP7Jerseys/blob/main/JerseysELTP18.js

**Comment by MrDenexi** [comment]
Have you tried doing it the old-fashioned way? 

Something like this:
https://github.com/jadeboy7/Tagpro-Texture-Pack-Script/blob/master/TagPro%20Texture%20Pack.user.js

Of course edit the @include to https.

**Comment by bash-tp** [comment]
Done.
