### ISSUE TITLE
Add TPM to fetch patterns

### ISSUE THREAD

**Issue by MrDenexi** [bash-tp/tagpro-vcr#6]
Hi,

I think a direct link to TPM replays could come in handy. I looked at the code and there's a 'fetch' hash that can be used. For TPM it would look like this:
`https://bash-tp.github.io/tagpro-vcr/#fetch=https://tpm.gg/Match/Replay/5a78993e-446a-4914-87b6-914dad0602c2`

To enable this a regex should be added to fetchPatterns in Appstate.ts:

```
const fetchPatterns = [
        new RegExp('^https://res\\.cloudinary\\.com/eggball/raw/upload/EggBall/[0-9]+.ndjson$'),
        new RegExp('^https://tpm.gg/Match/Replay/[^\s]*')
]
```
Tested the regex on https://regexr.com/. It should work.

After this I only have to convince the TPM devs to use the right url. 😁

**Comment by bash-tp** [comment]
Hey there, I already made this offer to hark. Currently this is not possible because tpm.gg is not serving up the necessary CORS headers. Once that's fixed, I'll be happy to add the pattern!

**Comment by MrDenexi** [comment]
If I just copy-paste a TPM replay url in the 'fetch from URL' input field, it fetches it without any issues.

Unless I misunderstood, it shouldn't be a problem (anymore?)

**Comment by bash-tp** [comment]
You're right, it's working now. I'll add the pattern in the next update.

**Comment by bash-tp** [comment]
Done.
