### ISSUE TITLE
Unable to record part of game from VCR

### ISSUE THREAD

**Issue by zmunro** [bash-tp/tagpro-vcr#8]
When I go to replay the game using the VCR web tool, the record button says "Video capture is disabled". Not sure how to fix this issue

**Comment by bash-tp** [comment]
There's this note on the homepage, you might have missed it 🙂

* Video capture (experimental!) is available only in Chrome, and only when WebGL Rendering is disabled. To allow video capture in Chrome, click on More Settings and turn off Video Settings > Enable WebGL Rendering. Playback performance might be worse.

Personally I get much better performance by leaving WebGL enabled and using OBS to capture the replay window. It's a lot less convenient but there are some inherent limitations in Chrome which are hard to work around.
